spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 20001124
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.lfz.demo.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level.com.lxs.demo.*: debug